[build]
  base = "."

  publish = "public/"

  # Default build command.
  command = "npm run build"

# Current Year Redirect

[[redirects]]
  from = "/"
  to = "/2018/ja/"
  status = 302

# Default Locale (2018)

[[redirects]]
  from = "/2018/"
  to = "/2018/ja/"
  status = 302

# SPA Fallbacks

[[redirects]]
  from = "/2018/en/*"
  to = "/2018/en/index.html"
  status = 200

[[redirects]]
  from = "/2018/ja/*"
  to = "/2018/ja/index.html"
  status = 200

[[redirects]]
  from = "/2017/*"
  to = "/2017/index.html"
  status = 200

[[redirects]]
  from = "/2016*"
  to = "/2016/index.html"
  status = 200

[[redirects]]
  from = "/2015/*"
  to = "/2015/index.html"
  status = 200


